version: '3.7'

services:
    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        image: butler
        container_name: butler
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_PASSWORD=$MONGO_PASSWORD
        ports:
            - '9003:9003'
        volumes:
            - .:/home/node/app
            - node_modules:/home/node/app/node_modules
            - logs:/home/node/app/logs
        networks:
            - app-network
        command: ./wait-for.sh db:27017 -- yarn start
    db:
        image: 'bitnami/mongodb:latest'
        container_name: db
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
        volumes:
            - dbdata:/data/db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
volumes:
    dbdata:
    node_modules:
    logs:
        driver: local
        driver_opts:
            type: none
            device: $PWD/logs
            o: bind
