version: '3.7'

services:
    butler:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mongo-db
        container_name: butler
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_PASSWORD=$MONGO_PASSWORD
        ports:
            - '9003:9003'
        volumes:
            - .:/app/
            - /app/node_modules
            - ./logs:/home/node/app/logs
        command: yarn start
    
    mongo-db:
        image: 'bitnami/mongodb:latest'
        container_name: db
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
        volumes:
            - dbdata:/data/db

volumes:
    dbdata: